### ISSUE TITLE
CalledFromWrongThreadException on FloorControllerView.refresh

### ISSUE THREAD

**Issue by aleksandra-majchrzak** [Mapwize/mapwize-app-android#4]
I built and installed the app, and in general it works ok, but sometimes when fiddling with the camera position, rotation and zoom, when entering and exiting the venue the app crashes because of CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

The same app from Google Play works fine.

**Comment by emerciercontexeo** [comment]
Hi,

Some fix has been done on the google play store version. It may explain why the app does not crash when you download it from here.

I will publish au new version on our next version update.

At this time, you can try to update the version on MapwizeForMapwize in the app build.gradle.

The last version is 1.3.9

Etienne

**Comment by aleksandra-majchrzak** [comment]
I updated the version, and it works fine now, thanks!
